@host=http://localhost:5050
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJpYXQiOjE2NTI4NjQzNTYsImV4cCI6MTY1Mjg4NTk1Nn0.ZjeyFQXV9LEgKiKGCTgtQCLUXivUaskFxklW_gg_JKU
Authorization:{{token}}
Content-Type: application/json


### get all users
GET {{host}}/users

### get 1 user from id
GET {{host}}/user/1

### ajouter un user
POST {{host}}/signup
Content-Type: application/json

{
    "mail": "bobby@mail.com",
    "lastname": "lose",
    "firstname": "bob",
    "pseudo": "losybob",
    "password":"losybob12",
    "password_confirmation": "losybob12"
     }

###se connecter
POST {{host}}/login
Content-Type: application/json

{
        "mail": "bobby@mail.com",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "losybob124"
    }

### update user
PATCH {{host}}/user
Authorization:{{token}}
Content-Type: application/json

{
  "mail": "bobby@mail.com",
    "lastname": "lose",
    "firstname": "bob",
    "pseudo": "losybob",
    "password":"losybob124",
    "password_confirmation": "losybob124"
}

### supprimer son compte
DELETE {{host}}/user
Authorization:{{token}}
Content-Type: application/json

###enregistrer un message
POST {{host}}/msg/save
Authorization:{{token}}
Content-Type: application/json

{
  "msg": "yolo"  
}

###envoyer un message
POST {{host}}/msg/send
Authorization:{{token}}
Content-Type: application/json

{
  "text": "yolo",
  "hook": "T03FENZNZML/B03G07MDWAD/w4SnLAs9iWrVCbyOydVvclVI"
  
}

